call config.cmd

sqlcmd -S %SERVER% -U %USER% -P %PASSWORD% -d %DATABASE% -i clean.sql

bcp PROPERTY_KIND in PROPERTY_KIND.dmp -f PROPERTY_KIND.fmt %PARAMS% -q
bcp FACILITY_CLASS in FACILITY_CLASS.dmp -f FACILITY_CLASS.fmt %PARAMS% -q
bcp COMMON_UNIVERSAL_PROPERTY in COMMON_UNIVERSAL_PROPERTY.dmp -f COMMON_UNIVERSAL_PROPERTY.fmt %PARAMS% -q
bcp FACILITY in FACILITY.dmp -f FACILITY.fmt %PARAMS% -q
bcp PROPERTY in PROPERTY.dmp -f PROPERTY.fmt %PARAMS% -q

@pause